<?php
use Zend\Json\Json;
/* @var $collector \JcBlog\Collector\MenuCollector */
$pages = array(); //$collector->getCollectedPages();
$pagesCount = count($pages);
?>
<div class="box gradient">

	<div class="title">

		<h4>
			<span>Páginas (<?php echo $pagesCount; ?>)</span>
		</h4>
		<a class="minimize" href="#" style="display: none;">Minimize</a>
	</div>
	<div style="padding-bottom: 0px; display: block;" class="content" id="page-menu">
		<div class="tabbable">
			<!-- Only required for left/right tabs -->
			<ul class="nav nav-pills">
				<li class="active"><a href="#tab1" data-toggle="tab">Mas recientes</a>
				</li>
				<li><a href="#tab2" data-toggle="tab">Todas</a></li>
				<li><a href="#tab3" data-toggle="tab">Buscar</a></li>
			</ul>

			<div class="tab-content">
				<div class="tab-pane active" id="tab1">
					<ul class="unstyled categorychecklist" data-wp-lists="list:page" id="pagechecklist">
					<?php foreach ($pages as $page): ?>
					<?php $jsonData = Json::encode(array('collector' => 'jc_blog_pages_collector', 'id' => $page->getId())); ?>
						<li>
						
							<label class="menu-item-title"><input type="checkbox"
								value='<?php echo $jsonData ?>' name="menu-item"> <?php echo $page->getTitle() ?></label>
								
							
						</li>
					<?php endforeach; ?>
					</ul>
				</div>
				<div class="tab-pane" id="tab2">
					<p>Howdy, I'm in Section 2.</p>
				</div>
				<div class="tab-pane" id="tab3">
					<p>Howdy, I'm in Section 3.</p>
				</div>
			</div>
		</div>


		<button id="submit-page-menu" class="btn btn-primary submit-add-to-menu" type="button">Añadir páginas</button>
		<br style="clear: both;"> <br style="clear: both;">
	</div>

</div>
<!-- End .box -->
